# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b684e6bb0d665f9bb1151f94351c0062"
name = "wishlist-app"
handle = "wishlist-app-318"
application_url = "https://actors-scheduling-solve-wash.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_products"

[auth]
redirect_urls = [
  "https://actors-scheduling-solve-wash.trycloudflare.com/auth/callback",
  "https://actors-scheduling-solve-wash.trycloudflare.com/auth/shopify/callback",
  "https://actors-scheduling-solve-wash.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://actors-scheduling-solve-wash.trycloudflare.com"
subpath = "wishlist"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
