# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8bce8d3d20810748fe9ab7af9137a960"
name = "wishlist-om"
handle = "wishlist-om"
application_url = "https://jackson-gauge-men-charleston.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_products,write_products"

[auth]
redirect_urls = [
  "https://jackson-gauge-men-charleston.trycloudflare.com/auth/callback",
  "https://jackson-gauge-men-charleston.trycloudflare.com/auth/shopify/callback",
  "https://jackson-gauge-men-charleston.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://jackson-gauge-men-charleston.trycloudflare.com"
subpath = "wishlist"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
